# jekyll-seo-tag
title: "Herman Melville"
description: "Official Author site for Herman Melville"
url: "http://www.jekyll-base-for-authors-thenewdynamic.com" # the base hostname & protocol for your site
author: []
twitter:
  username: therealhermanmelville
facebook:
  app_id: 
  publisher: 
  admins: 
logo: /uploads/cover-pachinko.jpg
google_site_verification:
github:
  username: budparr
owner: Min Jin Lee
# manifest
short_name: Herman Melville
display: fullscreen

# development meta data
image_url: http://thenewdynamic.imgix.net
google_analytics_id: UA-xxxxx-4
version: 3.0.3
incremental: true
#port: 3575


# Settings
production: false
bust_css_cache: false
full_rebuild: true
timezone: Etc/Zulu
compress_html:
  ignore:
    envs: [development]
  profile: false
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
plugins_dir:  ./_app/_plugins
layouts_dir:  ./_app/_layouts
includes_dir: ./_app/_includes

permalink: pretty

# CONTENT
exclude:
  - readme.md
  - todo.md
  - license.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - node_modules
  - sass
  - gulpfile.js
  - package.json
  - postcss.config.js

collections:
  landing_pages:
    output: true
    permalink: '/:path/'
  books:
    output: true
    permalink: '/:collection/:path/'
  events:
    output: false
defaults:
  - scope:
      path: ''
    values:
      layout: page-single
  - scope:
      path: ''
      type: 'landing_pages'
    values:
      layout: page-single
  - scope:
      path: ''
      type: pages
      permalink: /:basename/
    values:
      layout: page-single
  - scope:
      path: ''
      type: posts
    values:
      layout: page-single
      schema: BlogPosting