# jekyll-seo-tag
title: "Herman Melville"
description: "Official Author site for Herman Melville"
url: "http://www.jekyll-base-for-authors-thenewdynamic.com" # the base hostname & protocol for your site
author: []
twitter:
  username: therealhermanmelville
facebook:
  app_id:
  publisher:
  admins:
logo: /uploads/cover-pachinko.jpg
google_site_verification:
github:
  username: budparr
owner: Herman Melville
# manifest
short_name: Herman Melville
display: fullscreen

bindings:
  hardcover: Hardcover
  paperback: Paperback
  ebook: Ebook
  special: Special Edition
# bindings:
#   - hardcover
#   - paperback
#   - ebook
#   - special


# development meta data
image_url: http://thenewdynamic.imgix.net
google_analytics_id: UA-xxxxx-4
version: 3.0.3
incremental: false
#port: 3575


# Settings
production: false
bust_css_cache: false
timezone: Etc/Zulu
# compress_html:
#   ignore:
#     envs: [development]
#   profile: false
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
plugins_dir:  ./_app/_plugins
layouts_dir:  ./_app/_layouts
includes_dir: ./_app/_includes
paginate: 15
paginate_path: "/news/page:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - categories
  layout: 'listing-posts'
  permalinks:
    category: '/category/:name/'

# CONTENT
exclude:
  - readme.md
  - todo.md
  - license.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - node_modules
  - sass
  - gulpfile.js
  - package.json
  - postcss.config.js

future: true

collections:
  landing_pages:
    output: true
    permalink: '/:path/'
  events:
    output: true
    permalink: '/event/:path/'
  books:
    output: true
    permalink: '/:collection/:path/'
  genres:
    output: false
    permalink: '/:collection/:path/'

defaults:
  - scope:
      path: ''
    values:
      layout: page-single
  - scope:
      path: ''
      type: 'landing_pages'
    values:
      layout: page-single
  - scope:
      path: ''
      type: pages
      permalink: /:basename/
    values:
      layout: page-single
  - scope:
      path: ''
      type: posts
    values:
      layout: page-single
      schema: BlogPosting
  - scope:
      path: ''
      type: books
    values:
      layout: book
      schema: BlogPosting
      _comments:
        date: live on site date
  - scope:
      path: ''
      type: events
    values:
      layout: page-single

#design
button-classes: ' btn btn-outline col-12 sm-col-auto md-col-auto lg-col-auto mb2 gray border-silver'
base-layout-classes: ' mx3 sm-mx3 md-mx-auto lg-mx-auto lg-col-6 py2 lg-p3'
base-layout-classes-wide: ' clearfix mx3 sm-mx3 md-mx-auto lg-mx-auto lg-col-9 py2 lg-p3'
base-layout-classes-full: ' col-12 px3'


states:
  AK:
   name: Alaska
   abbreviation: AK

AL:
   name: Alabama
   abbreviation: AL

AS:
   name: American Samoa
   abbreviation: AS

AZ:
   name: Arizona
   abbreviation: AZ

AR:
   name: Arkansas
   abbreviation: AR

CA:
   name: California
   abbreviation: CA

CO:
   name: Colorado
   abbreviation: CO

CT:
   name: Connecticut
   abbreviation: CT

DE:
   name: Delaware
   abbreviation: DE

DC:
   name: District of Columbia
   abbreviation: DC

FM:
   name: Federated States of Micronesia
   abbreviation: FM

FL:
   name: Florida
   abbreviation: FL

GA:
   name: Georgia
   abbreviation: GA

GU:
   name: Guam
   abbreviation: GU

HI:
   name: Hawaii
   abbreviation: HI

ID:
   name: Idaho
   abbreviation: ID

IL:
   name: Illinois
   abbreviation: IL

IN:
   name: Indiana
   abbreviation: IN

IA:
   name: Iowa
   abbreviation: IA

KS:
   name: Kansas
   abbreviation: KS

KY:
   name: Kentucky
   abbreviation: KY

LA:
   name: Louisiana
   abbreviation: LA

ME:
   name: Maine
   abbreviation: ME

MH:
   name: Marshall Islands
   abbreviation: MH

MD:
   name: Maryland
   abbreviation: MD

MA:
   name: Massachusetts
   abbreviation: MA

MI:
   name: Michigan
   abbreviation: MI

MN:
   name: Minnesota
   abbreviation: MN

MS:
   name: Mississippi
   abbreviation: MS

MO:
   name: Missouri
   abbreviation: MO

MT:
   name: Montana
   abbreviation: MT

NE:
   name: Nebraska
   abbreviation: NE

NV:
   name: Nevada
   abbreviation: NV

NH:
   name: New Hampshire
   abbreviation: NH

NJ:
   name: New Jersey
   abbreviation: NJ

NM:
   name: New Mexico
   abbreviation: NM

NY:
   name: New York
   abbreviation: NY

NC:
   name: North Carolina
   abbreviation: NC

ND:
   name: North Dakota
   abbreviation: ND

MP:
   name: Northern Mariana Islands
   abbreviation: MP

OH:
   name: Ohio
   abbreviation: OH

OK:
   name: Oklahoma
   abbreviation: OK

OR:
   name: Oregon
   abbreviation: OR

PW:
   name: Palau
   abbreviation: PW

PA:
   name: Pennsylvania
   abbreviation: PA

PR:
   name: Puerto Rico
   abbreviation: PR

RI:
   name: Rhode Island
   abbreviation: RI

SC:
   name: South Carolina
   abbreviation: SC

SD:
   name: South Dakota
   abbreviation: SD

TN:
   name: Tennessee
   abbreviation: TN

TX:
   name: Texas
   abbreviation: TX

UT:
   name: Utah
   abbreviation: UT

VT:
   name: Vermont
   abbreviation: VT

VI:
   name: Virgin Islands
   abbreviation: VI

VA:
   name: Virginia
   abbreviation: VA

WA:
   name: Washington
   abbreviation: WA

WV:
   name: West Virginia
   abbreviation: WV

WI:
   name: Wisconsin
   abbreviation: WI

WY:
   name: Wyoming
   abbreviation: WY

AE:
   name: Armed Forces Africa
   abbreviation: AE

AA:
   name: Armed Forces Americas (except Canada)
   abbreviation: AA

AE:
   name: Armed Forces Canada
   abbreviation: AE

AE:
   name: Armed Forces Europe
   abbreviation: AE

AE:
   name: Armed Forces Middle East
   abbreviation: AE

AP:
   name: Armed Forces Pacific
   abbreviation: AP
